import type { Metadata } from "next";
export const metadata: Metadata = { title: "Ministries", description: "Ministries for children, youth, adults, and outreach at Beulah Baptist Church." };
const groups = [
  { id:"children", eyebrow:"Birth through elementary", title:"Children’s Ministry", image:"/images/children.jpg", intro:"We partner with families to help children know God’s Word, understand the gospel, and discover that church is a place where they are known and loved.", items:[["Nursery","Caring, age-appropriate care for little ones."],["Children’s Church","Bible teaching designed for young hearts and minds."],["AWANA","Scripture memory, discipleship, games, and friendships."],["VBS","A special seasonal week of Bible learning and fun."],["Special Activities","Family-friendly gatherings throughout the year."]] },
  { id:"youth", eyebrow:"Students", title:"Youth Ministry", image:"/images/youth.jpg", intro:"Students find a place to ask honest questions, grow in biblical faith, build strong friendships, and learn to live for Christ in everyday life.", items:[["Weekly Ministry","A consistent rhythm of Bible study, worship, and connection."],["Sunday School","Age-appropriate teaching and discussion."],["Missions","Opportunities to serve and share the gospel."],["Conferences","Focused times for growth, worship, and encouragement."],["Activities","Fun experiences that strengthen relationships."]] },
  { id:"adults", eyebrow:"Every season of life", title:"Adult Ministries", image:"/images/joy.jpg", intro:"Adult ministries create room for deeper relationships, spiritual growth, mutual encouragement, and joyful service.", items:[["Sunday School","Bible study and community for adults of all ages."],["Sisterhood","Women encouraging one another in faith and life."],["Man Church","Men growing as disciples, leaders, and friends."],["JOY Senior Adults","Fellowship and encouragement for senior adults."]] },
  { id:"outreach", eyebrow:"Beyond our walls", title:"Outreach Ministries", image:"/images/outreach.jpg", intro:"We want our neighbors to experience the love of Christ in practical ways. Outreach at Beulah combines generous service with a clear gospel witness.", items:[["Teachers Luncheon","A thoughtful expression of appreciation for local educators."],["Community Outreach","Serving real needs and building lasting relationships."],["Missions","Supporting and participating in gospel work near and far."]] },
];
export default function Ministries(){return <main>
  <section className="hero interior-hero"><div className="hero-content wrap"><p className="breadcrumbs">Home / Ministries</p><h1>Growing together.<br />Serving with purpose.</h1></div></section>
  <section className="section wrap"><div className="section-heading centered"><p className="eyebrow">Find your place</p><h2>Ministry at every age</h2><p>From the nursery to senior adulthood, there is a place to learn, connect, serve, and belong.</p></div><div className="expect-grid">{groups.map(g=><a className="plain-card" href={`#${g.id}`} key={g.id}><p className="eyebrow">{g.eyebrow}</p><h3>{g.title}</h3><p>{g.intro}</p></a>)}</div></section>
  {groups.map(g=><section className="ministry-section" id={g.id} key={g.id}><div className="wrap ministry-layout"><img src={g.image} alt="" /><div><p className="eyebrow">{g.eyebrow}</p><h2>{g.title}</h2><p>{g.intro}</p><div className="ministry-links">{g.items.map(([title,copy])=><div key={title}><strong>{title}</strong><span>{copy}</span></div>)}</div></div></div></section>)}
</main>}
