import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = { title: "About Us", description: "The mission, beliefs, leadership, and history of Beulah Baptist Church." };
export default function About() { return <main>
  <section className="hero interior-hero"><div className="hero-content wrap"><p className="breadcrumbs">Home / About Us</p><h1>Rooted in truth.<br />Growing in grace.</h1></div></section>
  <section className="section wrap content-grid"><aside className="side-nav"><a href="#mission">Our Mission</a><Link href="/what-we-believe">What We Believe</Link><a href="#pastor">Our Pastor</a><a href="#history">Church History</a></aside><article className="article">
    <section id="mission"><p className="eyebrow">Why we’re here</p><h2>Our Mission</h2><p className="large-copy">Love God. Love people. Make disciples.</p><p>Beulah Baptist Church exists to glorify God by proclaiming the good news of Jesus Christ, helping believers grow in His Word, caring for one another, and serving our neighbors near and far.</p><p>We are a Southern Baptist church and a member of the Tallapoosa Baptist Association.</p></section>
    <section id="beliefs"><p className="eyebrow">What we believe</p><h2>Anchored in Scripture</h2><p>As a Southern Baptist congregation, Beulah Baptist Church affirms the Baptist Faith and Message 2000. This statement summarizes the biblical convictions that shape our worship, teaching, ministries, and life together.</p><Link className="button navy" href="/what-we-believe">Explore What We Believe</Link></section>
    <section id="pastor"><p className="eyebrow">Shepherding God’s people</p><h2>Our Pastor</h2><div className="image-callout"><img src="/images/church-hero.jpg" alt="Beulah Baptist Church at sunset" /><div><h3>Timothy R. Davis</h3><p>Pastor Timothy R. Davis serves through faithful preaching, prayer, pastoral care, and a desire to see people know Christ and mature in their faith. Each message aims to explain Scripture clearly and apply it honestly to everyday life.</p></div></div></section>
    <section id="history"><p className="eyebrow">Since 1893</p><h2>Church History</h2><p>For generations, Beulah Baptist Church has gathered in faith, served families, and shared the gospel in its community. The buildings and ministries have grown over time, but the foundation remains the same: Jesus Christ and the truth of His Word.</p><p>Today, Beulah continues that legacy through worship, discipleship, missions, fellowship, and practical care for our neighbors. As a Southern Baptist congregation and member of the Tallapoosa Baptist Association, we cooperate with other churches to advance gospel ministry locally and beyond.</p></section>
  </article></section>
</main>; }
