import type { Metadata } from "next";
import Link from "next/link";
import { CHURCH, SITE_URL, absoluteUrl } from "../lib/site";
import { WideLogo } from "./site-logo";
import "./globals.css";

/**
 * Static metadata.
 *
 * This deliberately does not call `headers()`. Reading the request host in the
 * root layout forces every route in the app to render on demand, which is what
 * previously made all nine marketing pages dynamic. The origin now resolves at
 * build time from PUBLIC_BASE_URL (see lib/site.ts).
 */
export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: `${CHURCH.name} | Dadeville, Alabama`,
    template: `%s | ${CHURCH.name}`,
  },
  description: CHURCH.description,
  applicationName: CHURCH.name,
  alternates: { canonical: "/" },
  /*
   * Small, purpose-built icons. These all pointed at the full-size
   * logo-seal.png, which meant a 192KB download twice on every page load --
   * more weight than all the photos combined. Generated by
   * scripts/make-icons.mjs.
   */
  icons: {
    icon: [{ url: "/favicon-32.png", sizes: "32x32", type: "image/png" }],
    shortcut: "/favicon-32.png",
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180" }],
  },
  openGraph: {
    siteName: CHURCH.name,
    title: CHURCH.name,
    description: CHURCH.tagline,
    type: "website",
    locale: "en_US",
    url: SITE_URL,
    images: [
      {
        url: absoluteUrl("/og.png"),
        width: 1200,
        height: 630,
        alt: CHURCH.name,
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: CHURCH.name,
    description: CHURCH.tagline,
    images: [absoluteUrl("/og.png")],
  },
};

const primaryNav = [
  ["Home", "/"],
  ["Plan a Visit", "/plan-your-visit"],
  ["About", "/about"],
  ["Ministries", "/ministries"],
  ["Give", "/give"],
];
const secondaryNav = [
  ["What We Believe", "/what-we-believe"],
  ["Fellowships & Events", "/fellowships-events"],
  ["Text Updates", "/text"],
  ["Contact", "/contact"],
];
const nav = [...primaryNav, ...secondaryNav];

/**
 * Structured data so search engines can show service times, the address, and
 * a map pin directly in results. `Church` is the schema.org type Google
 * documents for places of worship.
 */
const structuredData = {
  "@context": "https://schema.org",
  "@type": "Church",
  name: CHURCH.name,
  description: CHURCH.description,
  url: SITE_URL,
  telephone: CHURCH.phone,
  image: absoluteUrl("/images/church-hero.jpg"),
  logo: absoluteUrl("/images/logo-seal.png"),
  address: {
    "@type": "PostalAddress",
    streetAddress: CHURCH.street,
    addressLocality: CHURCH.city,
    addressRegion: CHURCH.state,
    postalCode: CHURCH.zip,
    addressCountry: "US",
  },
  hasMap: `https://www.google.com/maps/search/?api=1&query=${CHURCH.mapQuery}`,
  event: [
    {
      "@type": "Event",
      name: "Contemporary Worship",
      startDate: "2026-01-04T09:00:00-06:00",
      eventSchedule: {
        "@type": "Schedule",
        byDay: "https://schema.org/Sunday",
        startTime: "09:00",
        repeatFrequency: "P1W",
      },
      location: { "@type": "Place", name: "Fellowship Hall" },
    },
    {
      "@type": "Event",
      name: "Sunday School",
      startDate: "2026-01-04T10:00:00-06:00",
      eventSchedule: {
        "@type": "Schedule",
        byDay: "https://schema.org/Sunday",
        startTime: "10:00",
        repeatFrequency: "P1W",
      },
    },
    {
      "@type": "Event",
      name: "Traditional Worship",
      startDate: "2026-01-04T11:00:00-06:00",
      eventSchedule: {
        "@type": "Schedule",
        byDay: "https://schema.org/Sunday",
        startTime: "11:00",
        repeatFrequency: "P1W",
      },
      location: { "@type": "Place", name: "Sanctuary" },
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        {/* First tabbable element, so keyboard users can jump the nav. */}
        <a className="skip-link" href="#main">
          Skip to content
        </a>

        <header className="site-header">
          <div className="wrap header-inner">
            <Link
              className="brand"
              href="/"
              aria-label={`${CHURCH.name} home`}
            >
              <WideLogo priority />
            </Link>

            <nav className="desktop-nav" aria-label="Main">
              {primaryNav.map(([label, href]) => (
                <Link href={href} key={href}>
                  {label}
                </Link>
              ))}
              <details className="more-menu">
                <summary>
                  More <span aria-hidden="true">⌄</span>
                </summary>
                <div>
                  {secondaryNav.map(([label, href]) => (
                    <Link href={href} key={href}>
                      {label}
                    </Link>
                  ))}
                </div>
              </details>
            </nav>

            <details className="mobile-menu">
              <summary aria-label="Open navigation">
                <span aria-hidden="true">Menu</span>
              </summary>
              <nav aria-label="Main">
                {nav.map(([label, href]) => (
                  <Link href={href} key={href}>
                    {label}
                  </Link>
                ))}
              </nav>
            </details>
          </div>
        </header>

        <div id="main">{children}</div>

        <footer className="site-footer">
          <div className="wrap footer-grid">
            <div className="footer-brand">
              <div className="footer-mark">
                <WideLogo alt={CHURCH.name} />
              </div>
              <p>Love God · Love People · Make Disciples</p>
            </div>
            <div>
              <h3>Visit</h3>
              <p>
                {CHURCH.street}
                <br />
                {CHURCH.city}, {CHURCH.state} {CHURCH.zip}
                <br />
                <a href={`tel:${CHURCH.phone}`}>{CHURCH.phoneDisplay}</a>
              </p>
              <a
                href={`https://www.google.com/maps/search/?api=1&query=${CHURCH.mapQuery}`}
                target="_blank"
                rel="noreferrer"
              >
                Get directions ↗
              </a>
            </div>
            <div>
              <h3>Gather</h3>
              <p>
                Sunday Worship · 9:00 &amp; 11:00 AM
                <br />
                Sunday School · 10:00 AM
                <br />
                Sunday &amp; Wednesday Nights · 6:00 PM
              </p>
            </div>
            <div>
              <h3>Explore</h3>
              {nav.map(([label, href]) => (
                <Link href={href} key={href}>
                  {label}
                </Link>
              ))}
            </div>
          </div>
          <div className="wrap footer-bottom">
            <span>
              © {new Date().getFullYear()} {CHURCH.name}
            </span>
            <span>Southern Baptist · Tallapoosa Baptist Association</span>
          </div>
        </footer>

        <script
          type="application/ld+json"
          // Built from the constants above, not user input.
          dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
        />
      </body>
    </html>
  );
}
